LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

# This file can be generated by ./gensrclist.sh
include Makefile.srcs

LOCAL_SRC_FILES := $(SRCS)

LOCAL_CFLAGS := -DANDROID
LOCAL_CFLAGS += -Wno-sequence-point -Wno-extra

LOCAL_C_INCLUDES := $(INCLUDE)

LOCAL_MODULE:= libFreeImage

include $(BUILD_STATIC_LIBRARY)
